name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Get ENV
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "ENV=$GIT_BRANCH" >> $GITHUB_ENV

      - run: yarn

      - run: echo $ENV

      - run: echo works
        if: env.ENV == 'main'

      - run: echo works 2
        if: env.ENV != 'main'
